# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 328cf55770572c8ddfa94ad18ea7513f187f26fcd9cc6cd82dc413921c516ef011a13c2e4c91246b618aab01f31f424d5f077b6469c3f4e42d46aeeae97c3dd7

test:
  secret_key_base: ab2874c2c10ea9e94e21779780ad862bdf6bcbf6502f5586537e19f9fba01f14269ba7ca71649f9d8421efcd5739474a0986266ddefbd49c696d2094dd53486f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
